# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	
	# Vanilla Debian 9 box
	config.vm.box = "debian/stretch64"
	config.vm.host_name = "debian9.box"

	# Network
	config.vm.network :forwarded_port, host: 3000, guest: 3000
	config.vm.network "private_network", ip: "10.10.10.10"

	# Configure provider
	config.vm.provider :virtualbox do |v|
		v.name = "debian9.box"
		v.memory = 1028
		v.cpus = 1
	end

	# Update
	config.vm.provision "shell", privileged: false, inline: <<-SHELL
		sudo apt-get update -y && sudo apt-get upgrade -y
	SHELL

end