# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
	
	# Vanilla Centos 7 box
	config.vm.box = "centos/7"
	config.vm.host_name = "centos7.box"

	# Network
	config.vm.network :forwarded_port, host: 3000, guest: 3000
	config.vm.network "private_network", ip: "10.10.10.10"

	# Configure provider
	config.vm.provider :virtualbox do |v|
		v.name = "centos7.box"
		v.memory = 1028
		v.cpus = 1
	end

	# Update
	config.vm.provision "shell", privileged: false, inline: <<-SHELL
		sudo yum update -y
	SHELL

end