# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	# Variables
	hostname = "debian8.box"
	locale = "en_GB.UTF.8"

	# Vanilla Debian 8 box
	config.vm.box = "debian/jessie64"

	config.vm.host_name = hostname
	config.vm.define hostname do |t|
	end

	# Network
	config.vm.network :forwarded_port, host: 3000, guest: 3000
	config.vm.network :forwarded_port, host: 8080, guest: 8080
	config.vm.network "private_network", ip: "10.10.10.10"

	# Configure provider
	config.vm.provider :virtualbox do |v|
		v.name = hostname
		v.memory = 1028
		v.cpus = 1
	end

	# Update
	config.vm.provision "shell", privileged: false, inline: <<-SHELL
		touch .hushlogin
		sudo hostnamectl set-hostname #{hostname} && sudo locale-gen #{locale}
		sudo apt-get update -y && sudo apt-get upgrade -y
		sudo apt-get install -q -y wget curl git vim
	SHELL

end
